module.exports = {
  AGENT_CODE: "AG019",
  SERVER_URL:
    "https://2ov8dxycl0.execute-api.ap-southeast-1.amazonaws.com/api/v1",
  
  LOGIN: "/login",
  PAGE_LOGIN_CAN_LOGIN_PLAY: "/api/v1/Authen/Token",
  // AFTER_LOGIN: "/lobby",
  AFTER_LOGIN: "/",
  TYPE_GAME: "/lobby/type-game",
  PROFILE: "/lobby/profile",
  PROMOTION: "/lobby/promotion",
  DEPOSIT_WITHDRAW: "/lobby/deposit-withdraw",
  DEPOSIT: "/lobby/deposit-withdraw/deposit",
  WITHDRAW: "/lobby/deposit-withdraw/withdraw",
  BANK_LIST: "/lobby/deposit/bank-list",
  BAG: "/lobby/bag",
  CASH_BACK: "/lobby/bag/cashback",
  UPLOAD_SLIP:'/upload',
  GAME_LIST: "/game-list",
  // GAME_LIST_MOBILE: "/game-list-mobile",

  LOGIN_TOKEN_DATA: "TOX_LOBBY_TOKEN",
  LOGIN_USER_DATA: "TOX_LOBBY_DATA",
  DATA_PROFILE: "DATA_PROFILE",
  DATA_BANK_LIST: "DATA_BANK_LIST",
  DATA_PROMOTION: "DATA_PROMOTION",
  BRAND_LIST: "BRAND_LIST",
  CASHBACK: "CASHBACK",
  CONFIG_CASHBACK: "CONFIG_CASHBACK",
  CONFIG_LINE: "CONFIG_LINE",
  CONFIG_LOBBY: "CONFIG_LOBBY",
  CONFIG_WITHDRAW: "CONFIG_WITHDRAW",
  SLIDE: "SLIDE",
  BANK_DEPOSIT: "BANK_DEPOSIT",

};
